### ISSUE TITLE
Team Checking

### ISSUE THREAD

**Issue by ghost** [the4chancup/autoATF#1]
I would like to know why is the program doing team checking. Shouldn't it be enough with the manager not being retard enough?

Also for the same reason it won't work with the VGL teams. Perhaps you should put either a confirmation if the team is not on the list, make the list editable or remove the checking altogether.

**Comment by NuclearBD** [comment]
Hey man, I've added a switch so you can disable the team list check. The newest binary is now on the wiki, just set Official_Teams_Only to 0 in the ini file and it'll work with any team you want.
